# Generated by Django 5.1.7 on 2025-03-17 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('user_input', models.TextField(verbose_name='사용자 입력')),
                ('process', models.TextField(verbose_name='처리 과정')),
                ('conversation', models.TextField(default='[]', verbose_name='대화 기록')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성 시간')),
                ('completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('result', models.TextField(blank=True, null=True, verbose_name='결과')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='즐겨찾기 여부')),
            ],
            options={
                'verbose_name': '작업',
                'verbose_name_plural': '작업 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
