# Generated by Django 5.1.7 on 2025-03-17 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_favorite',
        ),
        migrations.AlterField(
            model_name='task',
            name='conversation',
            field=models.TextField(verbose_name='대화 기록'),
        ),
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.TextField(verbose_name='처리 단계'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core.task', verbose_name='작업')),
            ],
            options={
                'verbose_name': '즐겨찾기',
                'verbose_name_plural': '즐겨찾기 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
